name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
          log-level: verbose
          dangerous-clean-slate: false
          state-name: .ftp-deploy-sync-state.json
          local-dir: ./

      - name: Create Directories
        uses: SteFSF/ftp-create-dirs-action@v1.0
        with:
          host: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          directories: |
            htdocs/api
            htdocs/control
            htdocs/views
            htdocs/public
